### PR TITLE
uses mathjax native cdn to fix max call stack issue

### PR DESCRIPTION
**Pull request by aaronik**
Fixes: https://github.com/Versal/player/issues/2121

### CODE REVIEW

**Comment by janpaul123** [comment]
Nice! Just wondering though, why have a whole bunch of other unrelated files been updated too? What happened there?

**Comment by aaronik** [comment]
I don't know, actually.  Could they have changed slightly?  I think every time you do a grunt (which I did before this PR) it pulls down new copies of the files from the interverse.  Could the maintainers have made small changes without changing the versions?

**Comment by janpaul123** [comment]
Possibly, but it scares me!

**Comment by janpaul123** [comment]
Or maybe uglify has some improvements?

**Comment by janpaul123** [comment]
Yeah, that would be my best guess:

screen shot 2014-08-07 at 10 18 58

**Comment by aaronik** [comment]
Good catch :)

**Pull request merged**
