### PR TITLE
Use SVG for mathjax, and load properly

### PR DESCRIPTION
**Pull request by janpaul123**
Because SVG is 25% faster and supported in modern browsers (IE >= 9).

Also refactored structure a bit in 37c3d9e, because it took me about 10 minutes to understand the build structure. :-( (My rule of thumb: if I can make something more understandable in the same time it took me to understand it in the first place, I'm gonna do it.)

### CODE REVIEW

**Comment by dylanpyle** [comment]
:+1:

**Comment by mereskin-zz** [comment]
@dylanpyle is this merged? Can Tekliner use mathjax2.2 and safe.js already?

Cc @dntst

**Comment by rjz** [comment]
@mereskin, sorry, we had to back this one out to un-break the player build. If this is blocking Tekliner, we'll work to get it back in ASAP.

**Comment by mereskin-zz** [comment]
Rj, it looks like it is blocking them. Thanks!

~ AM

**Comment by rjz** [comment]
Thanks, Andrey! I merged the follow-up and opened a player PR (https://github.com/Versal/player/pull/970) for the update.

**Pull request merged**
