### PR TITLE
Use Mathjax that supports a couple of variants

### PR DESCRIPTION
**Pull request by janpaul123**
Necessary for SAT math course.

### CODE REVIEW

**Comment by rjz** [comment]
Oh, shoot, just noticed this! Will give it a look ASAP.

**Comment by gravitypersists** [comment]
One thing - this might break the current expression gadget because it's expecting Asciimath input - ideally that gadget has a second property sheet field for selecting whether the input is Tex/Asciimath/Mathml.

**Comment by janpaul123** [comment]
The version I'm including here has Asciimath support though, right..?

**Comment by mereskin-zz** [comment]
@rjz Markdown gadget is broken because of this. Could you please verify and merge it?

**Comment by rjz** [comment]
@mereskin we'll get this verified and :+1: / :-1: today.

**Comment by rjz** [comment]
@janpaul123, this PR actually turns out to be a no-op at present—we're actually only using `config.js`, and even then the copy → player task is a bit opaque. Once that's all been `coffee -c`d, player breaks when skitch (is MathJax using it as a loader?) fails to find a dependency.

**Comment by janpaul123** [comment]
@rjz That's very strange, I had it running locally with success. There was something weird going on with `window.require` though (see my comment in https://github.com/Versal/tekliner-gadgets/pull/232)

**Pull request merged**
